name: Benchmarks

on:
  push:
    branches: 'master'
  pull_request:
    branches: [ '**' ]


env:
  RUST_BACKTRACE: 1
  PRUSTI_ASSERT_TIMEOUT: 60000

jobs:
  benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Set up the environment
        run: python x.py setup
      - name: Build with cargo
        run: python x.py build --release --all --verbose
      - name: Run benchmark with opt
        run: python x.py run-benchmarks opt
        env:
          PRUSTI_ENABLE_PURIFICATION_OPTIMIZATION: true
      - name: Print Result with opt
        run: cat benchmark-output/benchmark-opt*
      - name: Run benchmark without opt
        run: python x.py run-benchmarks noopt
        env:
          PRUSTI_ENABLE_PURIFICATION_OPTIMIZATION: false
      - name: Print Result without opt
        run: cat benchmark-output/benchmark-noopt*
